---
# yamllint disable rule:line-length
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  pgrubic_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Self test action
        id: action
        uses: ./
        with:
          src: "tests/sql"

      - name: Output installed pgrubic version
        run: echo ${{ steps.action.outputs.installed-pgrubic-version }}
