---
# yamllint disable rule:line-length
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Test default
        uses: ./
        with:
          src: "tests/sql"

  commands:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: lint
            args: "lint"
            pgrubic-version: "latest"
          - command: lint-report
            args: "lint --generate-lint-report"
            pgrubic-version: "latest"
          - command: lint-explicit-version
            args: "lint"
            pgrubic-version: "2.0.0"
          - command: format
            args: "format"
            pgrubic-version: "latest"
          - command: format-check
            args: "format --check"
            pgrubic-version: "latest"
          - command: format-diff
            args: "format --diff"
            pgrubic-version: "latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Test ${{ matrix.command }}
        uses: ./
        with:
          args: ${{ matrix.args }}
          pgrubic-version: ${{ matrix.pgrubic-version }}
          src: |
            tests/sql/V001__init.sql
            tests/sql/V003__file with spaces.sql
            tests/sql with spaces
